### ISSUE TITLE
Plugin Fails after a restart

### ISSUE THREAD

**Issue by mcraftpete** [ampayne2/DropParty#12]
[04:21:40] [Server thread/ERROR]: Error occurred while enabling DropParty v3.1 (Is it up to date?)
java.lang.NullPointerException
	at me.ampayne2.dropparty.parties.Party.updateChestList(Party.java:439) ~[?:?]
	at me.ampayne2.dropparty.parties.Party.<init>(Party.java:136) ~[?:?]
	at me.ampayne2.dropparty.PartyManager.<init>(PartyManager.java:55) ~[?:?]
	at me.ampayne2.dropparty.DropParty.onEnable(DropParty.java:85) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

**Comment by mcraftpete** [comment]
Hi,
So the plugin works fine on 1 of my servers , but on a prison server i have done everything , i have deleted plugin entirely and allowed it to recreate teh configs , done the normal process of creating and itempoints etc , and at end even test it working and works fine , but then after a server restart i get above error.
I have moved chests around and followed entire process again as i am sure it is an error with chests.

If you let me know that woudl be great.

**Comment by ampayne2** [comment]
Hi @mcraftpete ,

When the plugin is loaded, it gets all of the chests from the config files. As you noticed this issue is caused by one or more of the chests not loading correctly which could be caused by one of many things:

- The chest config could have been edited incorrectly but since you said you deleted the plugin entirely that is probably not the case.

- The location in the config could be invalid if the server can't find the world specified. I haven't personally tested this but if your server has multiple worlds it may be caused by the world not being loaded?

- The block at the location is not a chest. The plugin protects against players/normal causes of destroying chests but cannot do anything to prevent chests from being destroyed by other plugins such as WorldEdit.

I suggest making sure the config files were actually deleted and regenerated if you're using an online file manager or FTP client to edit your server files as in my experience they can become out of sync. Also make sure that all of the chest locations are actually chests, and that the world(s) are loaded on startup (if you're using a plugin like Multiverse a world may not be loaded until you teleport there or manually load it). If none of these are the issue let me know! I could have missed something since I haven't touched the code in 2 years and something could've changed on the bukkit/minecraft end.

**Comment by mcraftpete** [comment]
Hi,
Yes I checked all these things , its my mines world so I know its loaded or no one would be mining. I have redone it more then once and each time it has same result and same error , it works perfectly just not after a restart , what I just done was installed plugman , and after restart disabled and re-enabled plugin and it works fine , so something on loading up is preventing it from booting , it cant be chests as such as they wouldn't work at all after a plugman enable , it is completely fine after this just fails initially after a restart.

**Comment by mcraftpete** [comment]
Ok so i did lots more over the last hour and even teh plugman enabling is not working , obviously that risks corrupting plugin anyways so i re download fresh jars.
I am stuck , its a great plugin and i would love to use it , but cant have it unreliable :(c i ts literally server restarts that break it , i run 1.8.8 with viaversion , i whitelist server and have just me access it using 1.8 and still no joy.
Any help or possible fix would be really appreciated , i cant be only 1 as i am not a noob to plugins , been doing them 4 years now and run 3 networks :)
